// Definiciones de tipos de misiones y banco completo

export enum MissionType {
  COOPERATIVE = "cooperative",
  INDIVIDUAL = "individual",
  PUZZLE = "puzzle",
  MINIGAME = "minigame",
  CRAFTING = "crafting",
  SEQUENCE = "sequence",
  ASSEMBLY = "assembly",
  INSPECTION = "inspection",
  HEALING = "healing",
  QTE = "qte",
  REST = "rest",
  REPAIR = "repair",
  HARVEST = "harvest",
  CLEANING = "cleaning",
  MONITORING = "monitoring",
  OBSERVATION = "observation",
  ORGANIZATION = "organization",
  EXPLORATION = "exploration",
  PRECISION = "precision",
  RISK = "risk",
  PASSIVE = "passive",
  GLOBAL = "global",
  CRAFTING_RISK = "crafting_risk",
}

export interface MissionConfig {
  id: string;
  name: string;
  description: string;
  type: MissionType;
  minPlayers: number;
  area: string;
  duration: number; // milliseconds
  effects: {
    health?: number;
    oxygen?: number;
    hunger?: number;
    energy?: number;
    sanity?: number;
    fatigue?: number;
  };
  roles: string[]; // Roles requeridos/sugeridos ["engineer", "medic", etc]
}

export interface ActiveMission {
  id: string;
  missionId: string; // ID del MISSION_BANK
  config: MissionConfig;
  status: "pending" | "active" | "completed";
  progress: number; // 0-100
  startTime: number | null;
  endTime: number | null;
  playersInvolved: string[];
  assignedTo: string; // playerId
}

// Banco completo de misiones organizadas por área
export const MISSION_BANK: Record<string, MissionConfig[]> = {
  Oxygen: [
    {
      id: "oxygen_1",
      name: "Reparar el purificador de aire",
      description: "El purificador de aire necesita mantenimiento urgente",
      type: MissionType.COOPERATIVE,
      minPlayers: 2,
      area: "Oxygen",
      duration: 30000,
      effects: { oxygen: 10, energy: -10, fatigue: 10 },
      roles: ["engineer", "medic"],
    },
    {
      id: "oxygen_2",
      name: "Desinfectar el tanque de agua",
      description: "El tanque de agua requiere limpieza profunda",
      type: MissionType.CLEANING,
      minPlayers: 1,
      area: "Oxygen",
      duration: 25000,
      effects: { health: 5, energy: -5, sanity: 5 },
      roles: ["medic", "biologist"],
    },
    {
      id: "oxygen_3",
      name: "Redistribuir el flujo de oxígeno",
      description: "Ajustar las válvulas para optimizar la distribución",
      type: MissionType.PUZZLE,
      minPlayers: 1,
      area: "Oxygen",
      duration: 20000,
      effects: { oxygen: 20, energy: -15, fatigue: 5 },
      roles: ["engineer"],
    },
  ],
  Kitchen: [
    {
      id: "kitchen_1",
      name: "Recolectar los cultivos maduros",
      description: "Los cultivos están listos para la cosecha",
      type: MissionType.HARVEST,
      minPlayers: 1,
      area: "Kitchen",
      duration: 20000,
      effects: { hunger: 15, energy: -10 },
      roles: ["biologist"],
    },
    {
      id: "kitchen_2",
      name: "Preparar raciones nutritivas",
      description: "Cocinar alimentos para la tripulación",
      type: MissionType.CRAFTING,
      minPlayers: 1,
      area: "Kitchen",
      duration: 25000,
      effects: { hunger: 25, fatigue: 5 },
      roles: ["biologist", "medic"],
    },
    {
      id: "kitchen_3",
      name: "Control de plagas en la granja",
      description: "Eliminar plagas que amenazan los cultivos",
      type: MissionType.MINIGAME,
      minPlayers: 1,
      area: "Kitchen",
      duration: 30000,
      effects: { sanity: -5, hunger: 10, energy: -10 },
      roles: ["biologist"],
    },
  ],
  Energy: [
    {
      id: "energy_1",
      name: "Reiniciar el generador manualmente",
      description: "El generador necesita un reinicio de emergencia",
      type: MissionType.SEQUENCE,
      minPlayers: 1,
      area: "Energy",
      duration: 20000,
      effects: { energy: 20, fatigue: 10 },
      roles: ["engineer"],
    },
    {
      id: "energy_2",
      name: "Reemplazar baterías fundidas",
      description: "Las baterías están dañadas y deben ser reemplazadas",
      type: MissionType.COOPERATIVE,
      minPlayers: 2,
      area: "Energy",
      duration: 35000,
      effects: { energy: -15, fatigue: 15, health: 5 },
      roles: ["engineer"],
    },
    {
      id: "energy_3",
      name: "Ajustar el balance energético",
      description: "Optimizar la distribución de energía entre módulos",
      type: MissionType.PUZZLE,
      minPlayers: 1,
      area: "Energy",
      duration: 25000,
      effects: { sanity: 10, fatigue: 5 },
      roles: ["engineer", "scientist"],
    },
  ],
  Maintenance: [
    {
      id: "maintenance_1",
      name: "Reparar un dron averiado",
      description: "El dron de mantenimiento necesita reparación",
      type: MissionType.ASSEMBLY,
      minPlayers: 1,
      area: "Maintenance",
      duration: 30000,
      effects: { energy: 10, sanity: 5, fatigue: 10 },
      roles: ["engineer"],
    },
    {
      id: "maintenance_2",
      name: "Lubricar los mecanismos del módulo",
      description: "Los mecanismos necesitan lubricación preventiva",
      type: MissionType.INSPECTION,
      minPlayers: 1,
      area: "Maintenance",
      duration: 15000,
      effects: { energy: 5, fatigue: 5 },
      roles: ["engineer"],
    },
    {
      id: "maintenance_3",
      name: "Desbloquear puerta sellada",
      description: "Una puerta está bloqueada y debe ser abierta",
      type: MissionType.COOPERATIVE,
      minPlayers: 2,
      area: "Maintenance",
      duration: 25000,
      effects: { energy: -10, sanity: -5, fatigue: 15 },
      roles: ["engineer"],
    },
  ],
  Lab: [
    {
      id: "lab_1",
      name: "Analizar muestras contaminadas",
      description: "Examinar muestras para detectar contaminación",
      type: MissionType.PUZZLE,
      minPlayers: 1,
      area: "Lab",
      duration: 30000,
      effects: { sanity: 10, energy: -10 },
      roles: ["scientist", "biologist"],
    },
    {
      id: "lab_2",
      name: "Crear antídoto experimental",
      description: "Sintetizar un antídoto para una posible enfermedad",
      type: MissionType.CRAFTING_RISK,
      minPlayers: 1,
      area: "Lab",
      duration: 40000,
      effects: { health: 15, energy: -15 },
      roles: ["medic", "scientist"],
    },
    {
      id: "lab_3",
      name: "Recalibrar sensores biológicos",
      description: "Ajustar los sensores para lecturas precisas",
      type: MissionType.PRECISION,
      minPlayers: 1,
      area: "Lab",
      duration: 20000,
      effects: { energy: 5, sanity: 5, fatigue: 5 },
      roles: ["scientist"],
    },
  ],
  Psychology: [
    {
      id: "psychology_1",
      name: "Sesión grupal de relajación",
      description: "Realizar una sesión de relajación para la tripulación",
      type: MissionType.COOPERATIVE,
      minPlayers: 2,
      area: "Psychology",
      duration: 35000,
      effects: { sanity: 20, energy: 10, fatigue: -20 },
      roles: ["medic"],
    },
    {
      id: "psychology_2",
      name: "Juego de realidad virtual",
      description: "Usar el simulador VR para entretenimiento",
      type: MissionType.INDIVIDUAL,
      minPlayers: 1,
      area: "Psychology",
      duration: 20000,
      effects: { sanity: 10, energy: -5 },
      roles: [],
    },
    {
      id: "psychology_3",
      name: "Diario personal o meditación",
      description: "Tiempo de reflexión personal",
      type: MissionType.PASSIVE,
      minPlayers: 1,
      area: "Psychology",
      duration: 25000,
      effects: { sanity: 15, fatigue: -10 },
      roles: [],
    },
  ],
  Sleep: [
    {
      id: "sleep_1",
      name: "Dormir turno completo",
      description: "Descansar durante un ciclo completo de sueño",
      type: MissionType.REST,
      minPlayers: 1,
      area: "Sleep",
      duration: 45000,
      effects: { energy: 40, fatigue: -40, hunger: -10 },
      roles: [],
    },
    {
      id: "sleep_2",
      name: "Siesta rápida",
      description: "Tomar un descanso breve",
      type: MissionType.REST,
      minPlayers: 1,
      area: "Sleep",
      duration: 20000,
      effects: { energy: 15, fatigue: -20 },
      roles: [],
    },
    {
      id: "sleep_3",
      name: "Reparar literas dañadas",
      description: "Arreglar las camas para mejor descanso",
      type: MissionType.REPAIR,
      minPlayers: 1,
      area: "Sleep",
      duration: 25000,
      effects: { energy: -10, fatigue: 10 },
      roles: ["engineer"],
    },
  ],
  Medbay: [
    {
      id: "medbay_1",
      name: "Curar heridas leves",
      description: "Aplicar primeros auxilios a heridas menores",
      type: MissionType.HEALING,
      minPlayers: 1,
      area: "Medbay",
      duration: 15000,
      effects: { health: 15, energy: -5 },
      roles: ["medic"],
    },
    {
      id: "medbay_2",
      name: "Atender crisis médica",
      description: "Responder a una emergencia médica",
      type: MissionType.QTE,
      minPlayers: 1,
      area: "Medbay",
      duration: 30000,
      effects: { health: 25, energy: -15, fatigue: 10 },
      roles: ["medic"],
    },
    {
      id: "medbay_3",
      name: "Sintetizar medicina básica",
      description: "Crear suministros médicos esenciales",
      type: MissionType.CRAFTING,
      minPlayers: 1,
      area: "Medbay",
      duration: 25000,
      effects: { health: 10, sanity: 5 },
      roles: ["medic", "scientist"],
    },
  ],
  Dock: [
    {
      id: "dock_1",
      name: "Revisar integridad de la esclusa",
      description: "Inspeccionar la esclusa de aire",
      type: MissionType.INSPECTION,
      minPlayers: 1,
      area: "Dock",
      duration: 25000,
      effects: { oxygen: 5, fatigue: 10 },
      roles: ["engineer"],
    },
    {
      id: "dock_2",
      name: "Cargar suministros desde cápsula",
      description: "Transportar suministros desde la cápsula de carga",
      type: MissionType.COOPERATIVE,
      minPlayers: 2,
      area: "Dock",
      duration: 30000,
      effects: { hunger: 10, energy: 10, fatigue: 15 },
      roles: [],
    },
    {
      id: "dock_3",
      name: "Reparar vehículo auxiliar",
      description: "Arreglar el vehículo de exploración",
      type: MissionType.ASSEMBLY,
      minPlayers: 1,
      area: "Dock",
      duration: 35000,
      effects: { energy: -20, sanity: 5 },
      roles: ["engineer"],
    },
  ],
  Control: [
    {
      id: "control_1",
      name: "Restaurar comunicaciones",
      description: "Reparar el sistema de comunicaciones",
      type: MissionType.MINIGAME,
      minPlayers: 1,
      area: "Control",
      duration: 25000,
      effects: { sanity: 10, fatigue: 5 },
      roles: ["engineer", "scientist"],
    },
    {
      id: "control_2",
      name: "Analizar el estado del sistema",
      description: "Revisar todos los sistemas de la estación",
      type: MissionType.MONITORING,
      minPlayers: 1,
      area: "Control",
      duration: 20000,
      effects: { energy: 5, sanity: 5 },
      roles: ["scientist"],
    },
    {
      id: "control_3",
      name: "Enviar señal de auxilio",
      description: "Transmitir una señal de emergencia",
      type: MissionType.GLOBAL,
      minPlayers: 1,
      area: "Control",
      duration: 30000,
      effects: { sanity: 15, energy: -10 },
      roles: [],
    },
  ],
  Storage: [
    {
      id: "storage_1",
      name: "Inventariar recursos",
      description: "Organizar y contar todos los recursos",
      type: MissionType.ORGANIZATION,
      minPlayers: 1,
      area: "Storage",
      duration: 20000,
      effects: { sanity: 5, energy: -5 },
      roles: [],
    },
    {
      id: "storage_2",
      name: "Transportar suministros críticos",
      description: "Mover suministros esenciales a otros módulos",
      type: MissionType.COOPERATIVE,
      minPlayers: 2,
      area: "Storage",
      duration: 25000,
      effects: { fatigue: 15, energy: -15 },
      roles: [],
    },
    {
      id: "storage_3",
      name: "Reforzar contenedores dañados",
      description: "Reparar contenedores de almacenamiento",
      type: MissionType.REPAIR,
      minPlayers: 1,
      area: "Storage",
      duration: 20000,
      effects: { energy: 5, fatigue: 10 },
      roles: ["engineer"],
    },
  ],
  Biodome: [
    {
      id: "biodome_1",
      name: "Polinizar manualmente plantas raras",
      description: "Ayudar en la polinización de plantas especiales",
      type: MissionType.PRECISION,
      minPlayers: 1,
      area: "Biodome",
      duration: 30000,
      effects: { hunger: 15, sanity: 10, energy: -10 },
      roles: ["biologist"],
    },
    {
      id: "biodome_2",
      name: "Ajustar parámetros ambientales",
      description: "Optimizar temperatura y humedad del biodomo",
      type: MissionType.PUZZLE,
      minPlayers: 1,
      area: "Biodome",
      duration: 25000,
      effects: { oxygen: 10, health: 5, fatigue: 5 },
      roles: ["biologist", "scientist"],
    },
    {
      id: "biodome_3",
      name: "Recolectar muestra bioluminiscente",
      description: "Obtener muestras de organismos bioluminiscentes",
      type: MissionType.EXPLORATION,
      minPlayers: 1,
      area: "Biodome",
      duration: 35000,
      effects: { sanity: -5, energy: -10, health: 10 },
      roles: ["biologist", "scientist"],
    },
  ],
  Observatory: [
    {
      id: "observatory_1",
      name: "Registrar anomalías estelares",
      description: "Documentar fenómenos astronómicos inusuales",
      type: MissionType.OBSERVATION,
      minPlayers: 1,
      area: "Observatory",
      duration: 30000,
      effects: { sanity: 15, fatigue: 10 },
      roles: ["scientist"],
    },
    {
      id: "observatory_2",
      name: "Calibrar telescopio principal",
      description: "Ajustar el telescopio para observaciones precisas",
      type: MissionType.PRECISION,
      minPlayers: 1,
      area: "Observatory",
      duration: 20000,
      effects: { sanity: 5, energy: 5 },
      roles: ["scientist", "engineer"],
    },
    {
      id: "observatory_3",
      name: "Investigar señal desconocida",
      description: "Analizar una señal misteriosa del espacio",
      type: MissionType.RISK,
      minPlayers: 1,
      area: "Observatory",
      duration: 40000,
      effects: { sanity: 20, health: 10 },
      roles: ["scientist"],
    },
  ],
};

// Mapeo de roles crew a nombres de roles en misiones
export const ROLE_MAPPING: Record<string, string> = {
  crew_medic: "medic",
  crew_engineer: "engineer",
  crew_scientist: "scientist",
  crew_biologist: "biologist",
};